# wrangler.toml - Cloudflare configuration file
name = "nvrs-ts-v1"
compatibility_date = "2025-03-21"

[build]
command = "npm run build"
upload.format = "directory"

[site]
bucket = ".next/static"
entry-point = "."

[env.production]
workers_dev = true

# Next.js needs these headers
[build.upload]
format = "service-worker"

[build.environment]
NODE_VERSION = "20.0.0"