# wrangler.toml - Cloudflare configuration for static export
name = "nvrs-ts-v1"
compatibility_date = "2025-03-21"

# Static asset configuration
[site]
bucket = "./out"

# Build configuration
[build]
command = "npm run build"

# Environment configuration
[env.production]
workers_dev = true